import { defineConfig } from 'orval';

/**
 * Omit OpenAPI `info.version` from generated file banners so package/spec
 * version bumps do not dirty every generated source file.
 */
const generatedFileHeader = ({ title, description }: { title?: string; description?: string }) => [
  'Generated by orval',
  'Do not edit manually.',
  ...(title ? [title] : []),
  ...(description ? [description] : []),
];

export default defineConfig({
  api: {
    input: './openapi.json',
    output: {
      mode: 'tags-split',
      target: './src/generated/endpoints.ts',
      schemas: './src/generated/models',
      client: 'react-query',
      httpClient: 'fetch',
      clean: true,
      prettier: false,
      override: {
        header: generatedFileHeader,
        mutator: {
          path: './src/custom-fetch.ts',
          name: 'customFetch',
        },
      },
    },
  },
});
